### ISSUE TITLE
Tuning learning rates

### ISSUE THREAD

**Issue by bigaidream** [nicholas-leonard/drmad#6]

**Comment by bigaidream** [comment]
@nicholas-leonard  The `VW[j]` are always zeros, which stand for velocity of weights. 
Basically, [Line 289](https://github.com/nicholas-leonard/drmad/blob/master/lr_drmad_mnist.lua#L289) tries to get the difference between the last `params` and the current `params`. 
I made a deepcopy in [Line 281](https://github.com/nicholas-leonard/drmad/blob/master/lr_drmad_mnist.lua#L281) to save `previousParams`.  But they still seem the same. 

One possible reason is that I divide the range of `beta` = [0.001, 0.999] into too many slices to make the differences meaningful. If that's the case, I will use less slices.

**Comment by bigaidream** [comment]
After decreasing the number of slices of `beta` to 5, the problem remains. So somehow, `previousParams` and `params` refer to the same object. But I used `deepcopy` already.

**Comment by nicholas-leonard** [comment]
Fixed in https://github.com/nicholas-leonard/drmad/commit/0758d633339819974eef04b1b3acb2c99b23f071. 

@bigaidream Basically, deepcopy doesn't actually deep copy the tensors :) So I used [`t1 = nn.utils.recursiveCopy(t1, t2)`](https://github.com/torch/nn/blob/master/utils.lua#L133) instead.
